import React from "react";
import Head from "next/head";
import Grid from "@material-ui/core/Grid";
import { makeStyles } from "@material-ui/core/styles";
import { Formik } from "formik";
import * as Yup from "yup";
import Input from "../../../components/default/form/input";
import Button from "../../../components/default/form/button";
import Typography from "@material-ui/core/Typography";
import Box from "@material-ui/core/Box";
import Card from "@material-ui/core/Card";
import InputAdornment from "@material-ui/core/InputAdornment";
import Visibility from "@material-ui/icons/Visibility";
import { Person, Email } from "@material-ui/icons";
import VisibilityOff from "@material-ui/icons/VisibilityOff";
import IconButton from "@material-ui/core/IconButton";

// regex
const passwordRegex = /((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$/;

const useStyles = makeStyles((theme) => ({
  root: {
    flexGrow: 1,
  },
  paper: {
    padding: theme.spacing(2),
    textAlign: "center",
    color: theme.palette.text.secondary,
  },
  card: {
    padding: "36px",
    marginTop: "19px",
  },
}));

const ChangePassword = () => {
  const classes = useStyles();

  const [values, setValues] = React.useState({
    showComfirmPassword: false,
    currentPassword: false,
    showPassword: false,
  });

  const handleClickShowPassword = () => {
    setValues({
      ...values,
      showPassword: !values.showPassword,
    });
  };
  const handleClickComfirmPassword = () => {
    setValues({
      ...values,

      showComfirmPassword: !values.showComfirmPassword,
    });
  };
  const handleClickCurrentPassword = () => {
    setValues({
      ...values,
      currentPassword: !values.currentPassword,
    });
  };

  return (
    <div className={classes.root}>
      <Head>
        <title>Change Password</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid container spacing={3}>
        <Grid item xs={12} md={3} sm={12}></Grid>
        <Grid item xs={12} md={6} sm={12}>
          <Card className={classes.card}>
            <Box py={5}>
              <Typography variant="h4" color="primary" align="left">
                Change Password
              </Typography>
            </Box>
            <Formik
              initialValues={{
                currentPassword: "",
                password: "",
                comfirmPassword: "",
              }}
              validationSchema={Yup.object({
                currentPassword: Yup.string()
                  .min(6, "Current Password must be atleast 6 characters")
                  .matches(
                    passwordRegex,
                    "Password should contain atleast one number and one uppercase"
                  )
                  .required("Current Password is required"),
                password: Yup.string()
                  .min(6, "Password must be atleast 6 characters")
                  .matches(
                    passwordRegex,
                    "Password should contain atleast one number and one uppercase"
                  )
                  .required("Password is required"),
                comfirmPassword: Yup.string()
                  .oneOf(
                    [Yup.ref("password"), null],
                    "Password comfirmation fail"
                  )
                  .required("Comfirm password is required"),
              })}
              onSubmit={(values, actions) => {
                console.log(values);
              }}
            >
              {(props) => (
                <form onSubmit={props.handleSubmit}>
                  {/* Password */}
                  <Input
                    type={values.currentPassword ? "text" : "password"}
                    onChange={props.handleChange}
                    onBlur={props.handleBlur}
                    value={props.values.currentPassword}
                    label="Current Password"
                    name="currentPassword"
                    error={props.errors.currentPassword ? true : false}
                    errortext={props.errors.currentPassword}
                    InputProps={{
                      endAdornment: (
                        <InputAdornment position="start">
                          <IconButton
                            onClick={handleClickCurrentPassword}
                            edge="end"
                          >
                            {values.currentPassword ? (
                              <Visibility color="primary" />
                            ) : (
                              <VisibilityOff />
                            )}
                          </IconButton>
                        </InputAdornment>
                      ),
                    }}
                  />

                  {/* Password */}
                  <Input
                    type={values.showPassword ? "text" : "password"}
                    onChange={props.handleChange}
                    onBlur={props.handleBlur}
                    value={props.values.password}
                    label="Password"
                    name="password"
                    error={props.errors.password ? true : false}
                    errortext={props.errors.password}
                    InputProps={{
                      endAdornment: (
                        <InputAdornment position="start">
                          <IconButton
                            onClick={handleClickShowPassword}
                            edge="end"
                          >
                            {values.showPassword ? (
                              <Visibility color="primary" />
                            ) : (
                              <VisibilityOff />
                            )}
                          </IconButton>
                        </InputAdornment>
                      ),
                    }}
                  />

                  {/* Retype password */}
                  <Input
                    type={values.showComfirmPassword ? "text" : "password"}
                    onChange={props.handleChange}
                    onBlur={props.handleBlur}
                    value={props.values.comfirmPassword}
                    label="Retype Password"
                    name="comfirmPassword"
                    error={props.errors.comfirmPassword ? true : false}
                    errortext={props.errors.comfirmPassword}
                    InputProps={{
                      endAdornment: (
                        <InputAdornment position="start">
                          <IconButton
                            onClick={handleClickComfirmPassword}
                            edge="end"
                          >
                            {values.showComfirmPassword ? (
                              <Visibility color="primary" />
                            ) : (
                              <VisibilityOff />
                            )}
                          </IconButton>
                        </InputAdornment>
                      ),
                    }}
                  />

                  <Button label="Change password" type="submit" />
                </form>
              )}
            </Formik>
          </Card>
        </Grid>
        <Grid item xs={12} md={3} sm={12}></Grid>
      </Grid>
    </div>
  );
};

ChangePassword.layout = "DashboardLayout";
export default ChangePassword;
